/** Realistic content for the dev/demo seed (VTK IT team). */
import type { TagColor } from "@dopl/shared/palette";

export const people = [
  { email: "owner@dopl.test", name: "Olivia Owner", role: "OWNER" as const },
  { email: "ann@dopl.test", name: "Ann Peeters", role: "ADMIN" as const },
  { email: "bram@dopl.test", name: "Bram Janssens", role: "MEMBER" as const },
  { email: "chloe@dopl.test", name: "Chloé Maes", role: "MEMBER" as const },
  { email: "dries@dopl.test", name: "Dries Claes", role: "MEMBER" as const },
  { email: "emma@dopl.test", name: "Emma Wouters", role: "MEMBER" as const },
  { email: "guest@example.test", name: "Gert Gast", role: "GUEST" as const },
];

export const projects: Array<{
  identifier: string;
  name: string;
  color: TagColor;
  labels: Array<{ name: string; color: TagColor }>;
  titles: string[];
}> = [
  {
    identifier: "INFRA",
    name: "Infrastructure",
    color: "blue",
    labels: [
      { name: "proxmox", color: "orange" },
      { name: "docker", color: "blue" },
      { name: "backups", color: "teal" },
      { name: "monitoring", color: "purple" },
      { name: "hardware", color: "amber" },
    ],
    titles: [
      "Upgrade Proxmox node pve-02 to 9.1",
      "Move web container to port 8081 on app-01",
      "Rotate TLS certificates for *.vtk.be",
      "Set up off-site backups for the member database",
      "Replace failing disk in NAS bay 3",
      "Migrate Nextcloud to the new storage pool",
      "Add Grafana alert for disk usage above 85%",
      "Document the restore procedure for Postgres backups",
      "Consolidate docker-compose files into one repo",
      "Patch kernel on all Debian hosts",
      "Enable ZFS snapshots on pve-01",
      "Decommission the old ticketing VM",
      "Set up Uptime Kuma checks for public services",
      "Tune Postgres memory settings on db-01",
      "Rebuild the CI runner image with Node 24",
      "Move secrets from .env files into Vaultwarden",
      "Automate weekly restore tests",
      "Upgrade Traefik to v3 on the edge host",
      "Clean up unused Docker images and volumes",
      "Install UPS monitoring (NUT) for the server rack",
      "Right-size RAM on the analytics VM",
      "Set log retention for Loki to 30 days",
      "Replace fan in switch cabinet",
      "Create Ansible role for base Debian hardening",
      "Investigate high iowait on app-02",
    ],
  },
  {
    identifier: "NET",
    name: "Network",
    color: "teal",
    labels: [
      { name: "wifi", color: "blue" },
      { name: "firewall", color: "red" },
      { name: "dns", color: "purple" },
      { name: "cabling", color: "amber" },
    ],
    titles: [
      "Wi-Fi drops in the meeting room on the second floor",
      "Add VLAN for the event ticket scanners",
      "Renew the domain vtk.be before expiry",
      "Replace access point in the bar area",
      "Set up guest Wi-Fi captive portal for events",
      "Audit firewall rules on the OPNsense box",
      "Label all patch panel ports in the server room",
      "Move DNS zones to Cloudflare",
      "Configure DHCP reservations for printers",
      "Upgrade core switch firmware",
      "Enable IPv6 on the office network",
      "Run new cable to the storage room",
      "Measure Wi-Fi coverage before the open day",
      "Block outbound SMTP from the guest VLAN",
      "Set up WireGuard for remote admins",
      "Investigate packet loss on uplink",
    ],
  },
  {
    identifier: "HELP",
    name: "Helpdesk",
    color: "amber",
    labels: [
      { name: "account", color: "blue" },
      { name: "laptop", color: "grey" },
      { name: "printer", color: "orange" },
      { name: "google-workspace", color: "green" },
    ],
    titles: [
      "New board member needs a Google Workspace account",
      "Printer on the first floor shows paper jam error",
      "Reset 2FA for the treasurer's account",
      "Laptop for the new praeses won't connect to Wi-Fi",
      "Shared drive permissions for the events team",
      "Mailing list for the sports committee",
      "Projector in the auditorium has no signal",
      "Install LaTeX on the office PCs",
      "Recover deleted files from the marketing drive",
      "Set up email forwarding for the alumni address",
      "Order toner for the office printer",
      "Transfer ownership of the old committee drive",
      "Reset password for the photo committee account",
      "Configure calendar resources for meeting rooms",
      "Offboard last year's board members",
      "Add new members to the IT mailing list",
      "Webcam in the meeting room isn't detected",
      "Request: extra monitor for the secretariat",
    ],
  },
  {
    identifier: "SEC",
    name: "Security",
    color: "red",
    labels: [
      { name: "vulnerability", color: "red" },
      { name: "phishing", color: "orange" },
      { name: "audit", color: "purple" },
      { name: "policy", color: "grey" },
    ],
    titles: [
      "Phishing mail impersonating the treasurer",
      "Enforce 2FA for all Google Workspace admins",
      "Review access to the member database",
      "Update the password policy document",
      "Scan public hosts with nmap and triage findings",
      "Rotate API keys for the payment provider",
      "Enable DMARC reporting for vtk.be",
      "Set up alerts for failed SSH logins",
      "Remove stale SSH keys from servers",
      "Security awareness session for the new board",
      "Review GDPR data retention for event registrations",
      "Patch critical CVE in the reverse proxy",
      "Restrict admin panels to the VPN",
    ],
  },
  {
    identifier: "WEB",
    name: "Website & apps",
    color: "purple",
    labels: [
      { name: "frontend", color: "pink" },
      { name: "backend", color: "blue" },
      { name: "deploy", color: "teal" },
      { name: "bug", color: "red" },
    ],
    titles: [
      "Event page shows the wrong time zone",
      "Add Dutch translations to the ticket checkout",
      "Speed up the members list page",
      "Fix broken images on the sponsor page",
      "Set up staging environment for the website",
      "Migrate the website to Next.js 16",
      "Add iCal export for events",
      "Newsletter sign-up form doesn't validate emails",
      "Upgrade dependencies with known vulnerabilities",
      "Add accessibility checks to CI",
      "Dark mode for the member portal",
      "Deploy the new job board",
      "Optimize images on the homepage",
      "Error 500 when uploading a profile picture",
      "Add Plausible analytics",
      "Rewrite the cantus song book search",
    ],
  },
];

export const commentBank = [
  "I'll pick this up after the board meeting.",
  "Checked the logs — nothing obvious yet. Will look again tonight.",
  "Can we do this before the open day?",
  "Blocked on the supplier, they said early next week.",
  "Done on the first host, doing the rest tomorrow.",
  "This might be related to the firmware update last month.",
  "Added a note to the runbook.",
  "Who has access to the admin panel for this?",
  "Tested on staging, looks good.",
  "Let's keep this small and ship it.",
  "I pinged the committee, waiting for their answer.",
  "Rolled back, we need a maintenance window for this.",
];
